name: saludo

on:
  push:
    branches:
      - main
      - develop

jobs:
  saludo:
    runs-on: ubuntu-latest
    env:
      nombre: "Adriel Zumaeta"
    steps:
      - name: saludo desde main
        if: github.ref == 'refs/heads/main'
        run: echo "Hola desde main, soy $nombre"
        
      - name: saludo desde develop
        if: github.ref == 'refs/heads/develop'
        run: echo "Hola desde develop, soy $nombre"
